---
# handlers file for webserver
- name: Start Apache
  ansible.builtin.service: 
    name: httpd
    state: started
    enabled: yes

- name: Start PHP-FPM
  ansible.builtin.service:
     name: "{{ item }}"
     state: started 
     enabled: yes
  loop: "{{ ansible_facts.services | dict2items |selectattr('key', 'search', 'php.*fpm') |map(attribute='key') | list}}"