---
- name: Deploy Webserver
  hosts: webserver
  become: true
  become_user: root 
  become_method: sudo 
  #become_password: false 
  roles:
    - webserver
  
- name: Deploy Database Server
  hosts: database
  become: true
  become_user: root 
  become_method: sudo 
  #become_password: false 
  roles: 
     - database 


     
