---
# tasks file for database
- name: Install MariaDB 10.11
  ansible.builtin.dnf:
      name: 
        - mariadb1011
        - mariadb1011-server
      state: present
  notify: Start MariaDB

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install pip3
  ansible.builtin.dnf:
      name: python3-pip
      state: present
- name: Install PyMySQL
  ansible.builtin.pip:
      name: PyMySQL
      executable: pip3
      state: present
- name: Create Wordpress Database
  ansible.mysql.mysql_db:
    name: {{ mysql_db_name }}
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Generate password when it does not exist
  ansible.builtin.set_fact:
    mysql_user_password: >-
     {{ lookup('ansible.builtin.password',
               '/dev/null',
               length=24,
               chars=['ascii_letters', 'digits']) }}
  no_log: true

- name: Create DB user with privilege
  ansible.mysql.mysql_user:
    name: wpuser
    host: '%'
    password: "{{ mysql_user_password }}"
    priv: '{{ mysql_db_name }}.*:ALL'
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Save generated password
  ansible.builtin.copy:
    content: "{{ mysql_user_password }}\n"
    dest: "{{ mysql_password_file }}"
    owner: root
    group: root
    mode: '0600'
  delegate_to: localhost
  
- name: Show credentials
  ansible.builtin.debug:
    msg:
      database: "{{ mysql_db_name }}"
      username: "{{ mysql_user_name }}"
      password: "{{ mysql_user_password }}"
