---
# defaults file for deploy-ec2
#EC2 Instance's Names
web_name: "web01"
db_name: "db01"

# Instance and all other resource will create on this Region
aws_region: "us-east-2"

# AMI/Image used to create the instance, AMI ID varies in each AZ
ec2_image: "ami-06475e8f54266e38e" 

# Instance type
ec2_type: "t3.micro"

# SSH Key name, to connect to instances using SSH
ec2_key_name: "dbandweb-ansible"

# Security Group(SG) name for each Instance
sg_web: "webserver-ansible-01"
sg_db: "database-ansible-01"
