---
# tasks file for webserver
- name: Configure Apache/HTTPD in RedHat Family
  block: 
    - name: Install Apache/HTTPD and PHP Packages
      ansible.builtin.dnf:
        name:
          - httpd 
          - php
          - php-mbstring
          - php-zip
          - php-curl
          - php-mysqlnd
        state: present
      notify: 
        - Start Apache
        - Start PHP-FPM

    - name: Download Wordpress files
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.zip
        dest: "{{ DocumentRoot }}"
        remote_src: yes

    - name: Copy Wordpress files to DocumentRoot directory 
      ansible.builtin.copy:
        src: /var/www/html/wordpress/
        dest: "{{ DocumentRoot }}"
        remote_src: yes

    - name: Delete Wordpress download directory
      ansible.builtin.file:
        path: /var/www/html/wordpress
        state: absent

    - name: Change the permission of DocumentRoot
      ansible.builtin.file:
        path: "{{ DocumentRoot }}"
        state: directory
        owner: apache 
        group: apache 
        recurse: yes
  when: ansible_facts['os_family'] == "Redhat"

- name: Configure Apache in Debian Family
  block:
    - name: Install Apache2 and PHP Packages
      ansible.builtin.apt:
        name: 
          - apache2 
          - php
          - php-mbstring
          - php-zip
          - php-curl
          - php-mysqlnd
        state: present
      notify:
         - Start Apache2
         - Start PHP-FPM
         
    - name: Download Wordpress files
      ansible.builtin.unarchive:
        src: https://wordpress.org/latest.zip
        dest: "{{ DocumentRoot }}"
        remote_src: yes

    - name: Copy Wordpress files to DocumentRoot directory 
      ansible.builtin.copy:
        src: /var/www/html/wordpress/
        dest: "{{ DocumentRoot }}"
        remote_src: yes

    - name: Delete Wordpress download directory
      ansible.builtin.file:
        path: /var/www/html/wordpress
        state: absent

    - name: Change the permission of DocumentRoot
      ansible.builtin.file:
        path: "{{ DocumentRoot }}"
        state: directory
        owner: apache 
        group: apache 
        recurse: yes
  when: ansible_facts['os_family'] == "Debian"