- name: Create webserver EC2 Instances
  amazon.aws.ec2_instance:
    name: "{{ item }}"
    instance_type: t3.micro
    image_id: ami-028ba4d4ccb4b7b72
    key_name: anoop-aws-training
    network_interfaces:
        - assign_public_ip: true
    security_group: awslearning-webserver
    tags:
      type: webserver
      os: al3 
  loop:
    - web01
    - web02
  
- name: Create DB EC2 Instance
  amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro 
        image_id: ami-028ba4d4ccb4b7b72
        key_name: anoop-aws-training
        network_interfaces:
            - assign_public_ip: true
        security_group: awslearning-db
        tags: 
          type: database
          os: al3
  loop:
    - db01
