- name: Create Security Group for WebServer
  amazon.aws.ec2_security_group:
      name: "{{ sg_web | default('webserver-ansible-01', true) }}"
      description: "To allow http, https and SSH connections to webserver"
      region: "{{ aws_region | default('us-east-2', true) }}"
      state: present
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
          rule_desc: "Allow all outbound traffic"
- name: Create Security Group for DB Server
  amazon.aws.ec2_security_group:
      name: "{{ sg_db | default('database-ansible-01', true) }}"
      description: "To Allow MySQL connections from Webserver to DB, and also allow SSH"
      region: "{{ aws_region | default('us-east-2', true) }}"
      state: present
      rules:
        - proto: tcp
          group_name: "{{ sg_web | default('webserver-ansible-01', true) }}"
          from_port: 3306
          to_port: 3306
        
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
