---
# tasks file for lamponec2
- name: Include SG 
  ansible.builtin.include_tasks: security_group.yaml
- name: Include EC2 Instance 
  ansible.builtin.include_tasks: aws_ec2.yaml
- name: Include Webserver
  ansible.builtin.include_tasks: webserver.yaml
- name: Include DB setup 
  ansible.builtin.include_tasks: db.yaml
  